### ISSUE TITLE
Relative paths not supported

### ISSUE THREAD

**Issue by twsouthwick** [onovotny/SignService#12]
Example:

`dotnet SignClient.dll 'zip' -c .\build\SignClientSettings [...]`

Gives the error:

```
Exception:System.IO.FileNotFoundException: The configuration file '.\build\SignClientSettings.json' was not found and is not optional.
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at SignClient.Program.<DoMain>d__1.MoveNext() in C:\dev\SignService\src\SignClient\Program.cs:line 92
```

If I supply the full path for the configuration file, it is found and runs as expected.

**Comment by onovotny** [comment]
This is now supported when using the `netcoreapp2.0` version of the utility. (version 0.9.1, on NuGet now)
